[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
aeterna = "E3aVLq7oT4BFPjHRXaZmYupDJ9EZTG8At8oafLKzPMBG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
